"""empty message

Revision ID: 215edf86975c
Revises: 6dd246f347cf
Create Date: 2021-06-24 09:25:46.181860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215edf86975c'
down_revision = '6dd246f347cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
